version: "3"
services:
  mysql:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: volunteer_management
      MYSQL_TCP_PORT: 3309
    ports:
      - "3309:3309"